#!/bin/sh

LIT_NAME=$1
FILE_NAME=$(ls -l | awk -F' ' '/\.org/ {print $9}')
UNREAD=$(grep -n 'Unread' $FILE_NAME | cut -d ':' -f 1)
echo $LIT_NAME | awk -F'.' '{print "** [[./" $0 "][" $1 "]]"}' >> $FILE_NAME
{ head -n $UNREAD $FILE_NAME && awk -v unread_lin_num=$UNREAD 'NR>unread_lin_num' $FILE_NAME | sort -r; } 1<> $FILE_NAME
